### PR TITLE
CMake support

### PR DESCRIPTION
**Pull request by osimola**
This is more invasive than usual language additions, since CMake has one special full filename: CMakeLists.txt. There are not many file formats use this naming scheme, Make could perhaps be one.

### CODE REVIEW

**Comment by osimola** [comment]
There's a bug I didn't find last night, I'll reopen the PR after I have fixed that

**Comment by adamryczkowski** [comment]
I just wanted to say, that there are people like me, who are really tired of typing `-G ".*\.cmake"` on each ag invocation, and implementing a shortcut `--cmake` for this would be awesome. :-)

**Comment by adamryczkowski** [comment]
I am a C++ programmer myself. Perhaps I can help you with this bug? I've never contributed to the `ag` before.

**Comment by osimola** [comment]
The fixed pull request is here: https://github.com/ggreer/the_silver_searcher/pull/1141. There are some older pull requests that attempt the same thing. I think it's safe to say at this point that either ag is unmaintained or the maintainer really doesn't want to support Make, CMake, Rake and so on. My solution was to switch to Ripgrep, which supports Make and CMake file types and is overall a better piece of software.

**Pull request closed without merging**
