### PR TITLE
windows: add native colors support

### PR DESCRIPTION
**Pull request by avih**
It might need some cleanups or refactoring, let me know what you think.

### CODE REVIEW

**Comment by avih** [comment]
`Makefile.w32` is missing a `\` after `src/util.c`. I added it but github might be having issues and the push doesn't work right now but I'll push it when I can. I don't have a platform to test `Makefile.w32` so I missed it.

**Comment by ggreer** [comment]
Does this do the same thing as #333?

**Comment by avih** [comment]
It solves the same problem eventually using the same API, but with slightly different approaches.

PR  #333 provides an alternative generic `fprintf` function which parses the ansi codes in whatever goes through it and tries to apply whatever it can to the screen, while my approach is more limited where I've split the existing `fprintf` calls into strings and colors, where the color parts may go through the ansi-to-windows interpreter.

I haven't followed all the other code, but I also tried to play nicely with the options, default options and fallbacks (on case of pager/pipe).

**Comment by avih** [comment]
I actually have another patch to both simplify `set_color` and also make the colors handling more robust (can handle few more color codes, and overall more correct handling), but I'd appreciate feedback on the current approach first, and whether or not you wish to take it forward.

**Comment by avih** [comment]
Hmm.. you merged PR #333 after I submitted this PR...

I just tried it and noticed these issues:
- It doesn't build with MXE using the default `Makefile.am` since `print_w32.c` is missing. I included it temporarily and it now builds.
- It doesn't highlight the matching pattern by default or with other values which I tried to use for `--color-match`. It does highlight the path and line though, and it is affected by `--color-line` and `--color-path`.
- It doesn't seem to distinguish between normal and bright/bold colors (seem to always use bright/bold), doesn't seem to "understand" blink or underline, and possibly few more.

All of those were handled correctly at my patch. Since you already landed it though, I'll try to fix the current code.

**Comment by avih** [comment]
@mattn could you please comment on my findings above? are they only apparent on my build? or does your build exhibits them too?

**Comment by mattn** [comment]
print_w32.c should work on win32 native not cygwin/msys2. cygwin/msys2 can handle ansi escape sequence it-self.
Currently, I build ag with `mingw32-make -f Makefile.w32`. But you seems to want autotools. I'll look into it in next week.

**Comment by avih** [comment]
Updated the branch of this PR with some more pending updates I had, but closing this PR since #333 was merged.

I do have some fixes for it and I'll PR them.

**Pull request closed without merging**
