### PR TITLE
Support patterns beginning with a hyphen (grep -e analogue)

### PR DESCRIPTION
**Pull request by bishopb**
I have found myself searching for portions of object chains, like "->thread->get", but couldn't do that because the dash in the pattern was interpreted as an option.  In my home grown solution pre-ag, I used `grep -e` always, so I thought ag could get this little enhancement.  Unlike grep -e though, multiple patterns aren't supported.

Examples of new support:
- `ag -e '->thread'`
- `ag -e '->thread->'`
- `ag -e '->thread.*->'`

### CODE REVIEW

**Comment by bishopb** [comment]
Build fails because of:

> make: *** No rule to make target `doc/ag.1', needed by `all-am'.  Stop.

Should PR include regenerated `doc/ag.1`?

**Comment by aaronbauman** [comment]
+1 for this

**Comment by bishopb** [comment]
@aaronbauman While I'd like to have this for argument compatibility with `grep`, I've pretty much just been using the GNU bare double dash workaround: `ag -- '->foo('`.

**Comment by aaronbauman** [comment]
that works - thanks for the tip

**Pull request closed without merging**
