### PR TITLE
add support for BitBake source files

### PR DESCRIPTION
**Pull request by cardoe**
Add a --bitbake option which will search through the following files:

- .bb
- .bbappend
- .bbclass
- .inc
- .conf

### CODE REVIEW

**Comment by ggreer** [comment]
Won't there be a lot of false positives from matching .conf? I have lots of .conf files in my `~/code`, but none of them are related to BitBake.

**Comment by cardoe** [comment]
On 9/11/15 1:45 PM, Geoff Greer wrote:
> Won't there be a lot of false positives from matching .conf? I have lots
> of .conf files in my |~/code|, but none of them are related to BitBake.
> 

I wouldn't be be opposed to dropping .conf from the patch.

-- 
Doug Goldstein

**Comment by ggreer** [comment]
Ok. Feel free to change that and I'll merge it.

Sorry for the delay in responding to this PR. Work is a pretty big time-sink.

**Comment by ggreer** [comment]
Thanks!

**Pull request merged**
