### PR TITLE
Properly handle gitignores.

### PR DESCRIPTION
**Pull request by RedX2501**
I kindly ask someone to test this with valgrind as i developed this patch under cygwin.
- Loads parent .gitignore if in git project
- gitignore from the current path are also loaded even if not in git
  project
- Respects gitignore priorities, more local gitignore patterns to
  searched file override further away patterns
- In-file pattern ordering is respected
- Include patterns work
- Added many tests to check for correct gitignore handling
- Not terribly slow (tested with linux-master c517d838eb7d07bbe9507871fab3931deccff539)

With SSD, bitlocker encrypted partition

```
fixed gitignores:
-----------------

$ time ag source > /dev/null

real    0m15.636s
user    0m7.627s
sys     0m20.202s

broken gitignores (master 1ed4631d7745134a29b5e1b5097dd7dba37c97c2):
---------------------------

$ time ag source > /dev/null

real    0m14.425s
user    0m7.550s
sys     0m19.279s
```

This uses wildmatch from git. According to  #356 this might be problematic due to copyright issues.

### CODE REVIEW

**Comment by ggreer** [comment]
I'm sorry, but there's no way I can merge this. Most of the code you copied is GPL'd. That conflicts with the Apache 2.0 license.

**Comment by RedX2501** [comment]
Any ideas how i can solve these issues? I don't see a point in reimplementing wildmatch as it would only provide a chance for difference in behaviour...

**Comment by RedX2501** [comment]
I have asked the git-dev mailing list if there is possibility of re-licensing those files for Ag.
If it is not possible i'll look into using libgit2 for ignoring paths if that is ok with @ggreer .

**Comment by RedX2501** [comment]
There is an old email thread about it:http://thread.gmane.org/gmane.comp.version-control.git/259764/focus=259798

They seem to be fine relicensing it.

**Comment by ggreer** [comment]
Sorry, but getting an OK on a mailing list isn't enough. Git contributors don't sign a CLA, so they each hold copyright for their work. To make re-licensing legal, you'd have to get written approval from every single person who contributed to git's wildmatch code.

Patches like yours have been attempted at least two other times so far. One of the submitters was a git developer. The other was a friend and colleague who I started a company with. Unfortunately, license incompatibility, performance degradation, and code complexity conspire to make merging unlikely. Please don't get your hopes up. :(

**Comment by RedX2501** [comment]
Ok, most of them already agreed on the mailing list.

Then maybe you should consider switching your license to make supporting gitignores easier or dropping the gitignore support from your feature list...

Another option is to rewrite wildmatch but i don't like that solution as it leaves us open to subtle behaviour deviations.

**Comment by davvid** [comment]
FWIW I have a BSD-licensed wildmatch implementation at https://github.com/davvid/wildmatch in case that helps.  It passes [Git's wildmatch test suite](https://github.com/davvid/wildmatch/tree/master/tests/t3070-wildmatch.sh) and was developed by evolving the fnmatch implementation in OpenBSD.

**Comment by RedX2501** [comment]
@ggreer Would adding the implementation from davvid be ok? I'd take care of it.

**Pull request closed without merging**
