### PR TITLE
Added filetypes to test case

### PR DESCRIPTION
**Pull request by jschpp**
Test was failing. Now it shouldn't

### CODE REVIEW

**Comment by jschpp** [comment]
fixes #786 and should close #785

**Comment by rodfersou** [comment]
thanks @jschpp

**Comment by ggreer** [comment]
I'll defer to you Plone users, but searching .py and .xml seem like it'd cause tons of false positives.

**Comment by rodfersou** [comment]
@ggreer in our codebase it is normal to search into ``.xml`` files where we create profile configuration.

In Plone we just use ``.xml`` files in this case.

**Pull request merged**
