### PR TITLE
Don't alter casing if the file pattern is lowercase

### PR DESCRIPTION
**Pull request by Arkanosis**
Closes ggreer/the_silver_searcher#744.

### CODE REVIEW

**Comment by Arkanosis** [comment]
Anything I can do to make testing / merging easier?

Maybe with a more complete description of the bug:

`-S` / `--smart-case` is expected to make ag case-insensitive for regexps that are fully lowercase, and only in this case. Currently, if the *file* pattern (ie. with `-G`) is lowercase, ag becomes case-insensitive not only for the *file* pattern, but for the *search* pattern as well. ag should be case-insensitive for the *search* pattern only if the *search* pattern itself is lowercase.

The proposed changeset fixes this side-effect.

Side note: in my opinion, having distinct smart case flags for the *file* pattern and the *search* pattern would be better: there's no reason for the user to systematically want the same matching mode for both patterns.

Best regards,

**Comment by ggreer** [comment]
What happens if I run `ag -i 'BLAH.*'` ?

**Comment by Arkanosis** [comment]
Indeed, some stupid mistake on my part. It does run case-insensitive search on the file content, but not on the file name. I did not intend to change this behavior. The updated PR fixes this and passes the new test case. Thanks.

It stills bugs me to have the same `-i` / `-s` / `-S` flags to control the case-sensitivity of both the files names and the files contents, though, but that could be the subject of another PR.

**Comment by ggreer** [comment]
Thanks for being patient.

I'm not super-concerned about those flags applying to both text and filename search. I think the behavior you want is best served by chaining invocations.

**Pull request merged**
