### PR TITLE
Zip

### PR DESCRIPTION
**Pull request by jschpp**
Added zip processing
First step to solving #743 

Missing at this point are test cases and an opinion from @ggreer whether he likes it or not.

Testing it with a simple file (and my ebook Library ^^) works

### CODE REVIEW

**Comment by jschpp** [comment]
This doesn't compile. I need to modify .travis.yml. I'll open a new one after testing it on travis.

**Comment by zbstof** [comment]
Will try to test also

**Comment by jschpp** [comment]
When you try it you need to have at least libzip-1.0 installed
I'm working on [a new branch](https://github.com/jschpp/the_silver_searcher/tree/zip) to reflect this.

**Comment by jschpp** [comment]
@zbstof have a look at the new pr #843

**Pull request closed without merging**
