### PR TITLE
Add support for ~/.agrc default config options

### PR DESCRIPTION
**Pull request by schlosna**
I can't live without my default options, so this adds support for ~/.agrc similar to .ackrc

* Load .agrc configuration file from user's home directory if available.
* CLI options take precedence over .agrc options

### CODE REVIEW

**Comment by djanowski** [comment]
@schlosna Can you merge current master? Maybe that way we have *some* chance of getting this upstream?

**Comment by decaff** [comment]
I moved  @schlosna's code into 2 new source files (makes it easier to merge) and added the config file hierarchy listed above by @Zearin .  Commit is [here](https://github.com/decaff/the_silver_searcher/commit/f4336d8ca9bfc1dd8f67fd38e5e4c37c2670998c) .  Hope this helps.

**Comment by blueyed** [comment]
@decaff 
Seems to be worth a separate / follow-up PR then?!

**Comment by decaff** [comment]
Umm,  I'm new to github.  So, I'm unfamiliar with the protocol for things like this.  I assume that Geoff will merge if he approves and if he has time to review the code.

**Comment by blueyed** [comment]
@decaff 
Your commit will be lost/forgotten about probably, and this PR here appears to be stale.
I therefore think that creating a new PR with your commit (in a separate branch) is the way to go.

**Comment by nhooey** [comment]
If you could let us all know what the new pull request is, that would be great. I think we're all really excited about this change.

**Comment by decaff** [comment]
Hmmm, I can barely chew gum and walk it comes to git.  So, is this the desired outcome?

1) @decaff creates a new, local branch off Geoff's master
2) I merge just the .agrc changes
3) Push the branch back up to github
4) Come back here and announce the branch

Is this what is desired?

**Comment by blueyed** [comment]
@decaff 
Yes, that's what I've meant.  Keeping it in a separate branch makes it easier / possible to distinguish feature sets.

But given how this PR has rotten over the months, without any feedback from @ggreer you should not expect too much from it (in the near future).. :/
However, it's still better than only having linked a commit in a comment.

After all, your effort combines the efforts from this PR and should be seen / handled as its successor.

Thanks!

**Comment by blueyed** [comment]
@decaff 
About your 2nd point: you would basically `git cherry-pick` your commit into the new branch - I'm not sure that's what you've meant.

**Comment by decaff** [comment]
I'll give it a shot.

**Comment by decaff** [comment]
That was really unpleasant.  Branch has been [created](https://github.com/decaff/the_silver_searcher/commit/5d50f598f3f0cc03d49fb4f01cb29606c14406cd) . Found a bug in the line counting code while testing my manual merge. Fixed same.

**Comment by blueyed** [comment]
> That was really unpleasant.

Why?

> Branch has been created

But no PR yet?  The link to the branch appears to be: https://github.com/ggreer/the_silver_searcher/compare/master...decaff:config-file-support

> Found a bug in the line counting code while testing my manual merge. Fixed same.

But not in a separate commit?
Wouldn't it be a bugfix for `ag` in general (for its master branch)?  Then it should be a separate PR/issue/commit.

**Comment by decaff** [comment]
Bug in **my** line counting code in ag_rc.c .  

Unpleasant because I have no idea how to use git, beyond saving changes and pushing stuff to github.  I eventually gave up and merged the changes by hand.  Better safe than trashing my local repository.

I'll push the button for a pull request...

**Comment by blueyed** [comment]
> Unpleasant because I have no idea how to use git, beyond saving changes and pushing stuff to github

You'll hopefully get used to it.

The basic steps would have been (from the origin/master branch):

    # Create your branch
    % git checkout -b config-file-support
    # Cherry-pick your previous commit
    % git cherry-pick f4336d8
    # Register your origin/fork with Git
    % git remote add decaff https://github.com/decaff/the_silver_searcher
    # Push your branch to your fork.
    % git push decaff config-file-support

But you got that figured out.
I recommend using https://github.com/github/hub/ for advanced commands with `git` when used with Github.

**Comment by blueyed** [comment]
Given that there's https://github.com/ggreer/the_silver_searcher/pull/701 now, this PR could be closed probably.  (please note that I have not looked at the code)

**Comment by schlosna** [comment]
Thanks @decaff , closing this PR in favor or #701.

**Comment by decaff** [comment]
PR #709 supersedes #701 .  709 is up-to-date with master and passes the clang format tests.

**Pull request closed without merging**
