### PR TITLE
Add filetypes for Chapel language

### PR DESCRIPTION
**Pull request by ben-albrecht**
[Chapel](http://chapel.cray.com/) is an [open-source](https://github.com/chapel-lang/chapel) language built for productive parallel computing at scale.

I have added the Chapel source filetype: `.chpl`.

I have also formatted `CONTRIBUTING.md` for 80 character lines (a trivial edit for retriggering the previously broken Travis build)

### CODE REVIEW

**Comment by ben-albrecht** [comment]
Pinging @ggreer for review

**Comment by ggreer** [comment]
Can you kill the changes to `CONTRIBUTING.md` so that it's just the first commit? I don't like to pollute commit history if I can help it.

**Comment by ben-albrecht** [comment]
Done!

**Comment by ggreer** [comment]
Ah, I meant rewrite history so the commit didn't exist.

It's OK though. I've cherry-picked 36ad19f, so your change is in master now. Thanks!

**Pull request closed without merging**
